### ISSUE TITLE
Cannot join cluster

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-jgroups#18]
Once the cluster is created, other host cannot join it:

```
io.vertx.core.VertxException: org.jgroups.StateTransferException: state transfer failed
    at io.vertx.java.spi.cluster.impl.jgroups.CacheManager.start(CacheManager.java:105)
    at io.vertx.java.spi.cluster.impl.jgroups.JGroupsClusterManager.lambda$join$110(JGroupsClusterManager.java:179)
    at io.vertx.java.spi.cluster.impl.jgroups.JGroupsClusterManager$$Lambda$4/1348949648.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:296)
    at io.vertx.core.impl.ContextImpl$$Lambda$6/575335780.run(Unknown Source)
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$327(OrderedExecutorFactory.java:91)
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$5/466002798.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.jgroups.StateTransferException: state transfer failed
    at org.jgroups.JChannel.getState(JChannel.java:608)
    at org.jgroups.JChannel.getState(JChannel.java:534)
    at org.jgroups.JChannel.getState(JChannel.java:521)
    at io.vertx.java.spi.cluster.impl.jgroups.CacheManager.start(CacheManager.java:103)
    ... 9 more
Caused by: java.lang.RuntimeException: java.io.EOFException
    at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:682)
    at org.jgroups.JChannel.up(JChannel.java:699)
    at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:1029)
    at org.jgroups.protocols.Locking.up(Locking.java:270)
    at org.jgroups.protocols.COUNTER.up(COUNTER.java:202)
    at org.jgroups.protocols.pbcast.StreamingStateTransfer.setStateInApplication(StreamingStateTransfer.java:284)
    at org.jgroups.protocols.pbcast.StreamingStateTransfer$2.run(StreamingStateTransfer.java:489)
    ... 1 more
Caused by: java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2328)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2797)
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at io.vertx.java.spi.cluster.impl.jgroups.services.DefaultRpcMapService.readFrom(DefaultRpcMapService.java:100)
    at io.vertx.java.spi.cluster.impl.jgroups.CacheManager.setState(CacheManager.java:98)
    at org.jgroups.blocks.MessageDispatcher.handleUpEvent(MessageDispatcher.java:594)
    at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:679)
    ... 7 more
```

**Comment by cescoffier** [comment]
This is using the default configuration.

Applications are launched using: `-Djava.net.preferIPv4Stack=true -Djgroups.bind_addr=192.168.1.29`

**Comment by fmarinelli** [comment]
Thanks, I will check it ASAP

**Comment by fmarinelli** [comment]
Did you use a test case or a normal application with vertx stack?

**Comment by cescoffier** [comment]
Thanks, if I get this working it can be included in vert.x 3.2.0 as technical preview.

**Comment by cescoffier** [comment]
Let me share my application.

**Comment by cescoffier** [comment]
Here it is: https://github.com/cescoffier/jgroups--18-reproducer

Two applications: ProducerApp and ConsumerApp. 

It should be "runnable" from your IDE.

You will need to change the IP I've hardcoded inside

**Comment by fmarinelli** [comment]
Thanks

**Comment by cescoffier** [comment]
Fixed.
